# Generated by Django 5.1.5 on 2025-01-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento', '0002_festa_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('estado', models.CharField(choices=[('RJ', 'RJ'), ('SP', 'SP'), ('MG', 'MG'), ('ES', 'ES')], max_length=2)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('convidado', 'Por Convidado'), ('unico', 'Único'), ('hora', 'Por Hora')], max_length=10)),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='evento.festa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='custo.fornecedor')),
            ],
        ),
    ]
