# Generated by Django 5.1.5 on 2025-01-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convidado', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parentes',
            new_name='Parente',
        ),
    ]
