# Generated by Django 5.1.5 on 2025-01-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidado', '0002_rename_parentes_parente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='convidado',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
