# Generated by Django 5.1.5 on 2025-01-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidado', '0003_alter_convidado_email_alter_convidado_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parente',
            name='idade',
            field=models.CharField(choices=[('AD', 'Adulto'), ('CR', 'Criança'), ('BB', 'Bebê')], default='AD', max_length=2),
        ),
    ]
