# Generated by Django 5.1.5 on 2025-01-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidado', '0004_parente_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='cervejeiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parente',
            name='cervejeiro',
            field=models.BooleanField(default=False),
        ),
    ]
