# Generated by Django 5.1.5 on 2025-01-22 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidado', '0005_convidado_cervejeiro_parente_cervejeiro'),
        ('evento', '0006_remove_festa_latitude_remove_festa_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidado',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convidados', to='evento.festa'),
        ),
    ]
