# Generated by Django 5.1.5 on 2025-01-22 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidado', '0006_alter_convidado_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parente',
            name='convidado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentes', to='convidado.convidado'),
        ),
    ]
