# Generated by Django 5.1.5 on 2025-01-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidado', '0007_alter_parente_convidado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErroConfirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_incorreto', models.CharField(max_length=100)),
                ('numero_whatsapp_incorreto', models.CharField(max_length=11)),
                ('link', models.URLField()),
                ('criado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='convidado',
            name='convite_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
