# Generated by Django 5.1.5 on 2025-01-28 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convidado', '0008_erroconfirmacao_convidado_convite_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convidado',
            name='nao_vai',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LogEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(auto_now=True)),
                ('registro', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convidado.convidado')),
            ],
        ),
    ]
