# Generated by Django 5.1.5 on 2025-01-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convidado', '0009_convidado_confirmado_convidado_nao_vai_logeventos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convidado',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='convidado',
            name='nao_vai',
        ),
    ]
