# Generated by Django 5.1.5 on 2025-01-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festa',
            name='horas',
            field=models.DecimalField(decimal_places=0, default=4, max_digits=2),
        ),
    ]
