# Generated by Django 5.1.5 on 2025-01-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_alter_festa_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='festa',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='festa',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='festa',
            name='compl_endereco',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='festa',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='festa',
            name='estado',
            field=models.CharField(choices=[('RJ', 'RJ')], default='RJ', max_length=2),
        ),
    ]
