# Generated by Django 5.1.5 on 2025-01-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_festa_bairro_festa_cidade_festa_compl_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festa',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='festa',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
