# Generated by Django 5.1.5 on 2025-01-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_festa_latitude_festa_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festa',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='festa',
            name='longitude',
        ),
        migrations.AddField(
            model_name='festa',
            name='GPS',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
