# Generated by Django 5.1.5 on 2025-01-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_remove_festa_latitude_remove_festa_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festa',
            name='hash_evento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
